version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file: backend.env
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    restart: always
    networks:
      - app-network

  db:
    image: postgres:17
    restart: always
    env_file: secret.env
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
