spring.profiles.active=demo
spring.application.name=health-me

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=false

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret=MySuperSecretKeyForDemo2026ThisIsLongEnough
jwt.expiration=86400000
# refresh token = 14 days
jwt.refreshExpirationMs=1209600000 