# Production environment database configuration
spring.datasource.url=${DEV_DB_URL}
spring.datasource.username=${DEV_DB_USERNAME}
spring.datasource.password=${DEV_DB_PASSWORD}

frontend.url=http://localhost:5173

