import hainaneseChickenRice from '@/assets/images/hainanese-chicken-rice.webp';
import tomYumKung from '@/assets/images/tom-yum-kung.webp';
import thaiPapayaSalad from '@/assets/images/thai-papaya-salad.webp';
import padThaiWithFreshShrimp from '@/assets/images/pad-thai-with-fresh-shrimp.webp';
import greenCurryWithChicken from '@/assets/images/green-curry-with-chicken.webp';

export const thaiMenu = [
  {
    id: 1,
    name: 'ข้าวมันไก่',
    description: 'ข้าวมันหอม ๆ เสิร์ฟพร้อมไก่นุ่ม ๆ และน้ำจิ้มสูตรเด็ด',
    category: 'อาหารจานเดียว',
    image: hainaneseChickenRice,
    protein: 35,
    fat: 15,
    carbs: 60,
    calories: 450,
    baseIngredients: [
      { name: 'ข้าวหอมมะลิ', quantity: 1, unit: 'ถ้วย' },
      { name: 'ไก่', quantity: 1, unit: 'ตัว' },
      { name: 'น้ำมันไก่', quantity: 2, unit: 'ช้อนโต๊ะ' },
      { name: 'กระเทียม', quantity: 5, unit: 'กลีบ' },
      { name: 'ขิง', quantity: 2, unit: 'แง่ง' },
      { name: 'เกลือ', quantity: 1, unit: 'ช้อนชา' },
      { name: 'น้ำซุปไก่', quantity: 4, unit: 'ถ้วย' },
    ],
    steps: [
      { step: 1, instruction: 'ล้างไก่ให้สะอาด แล้วต้มในน้ำเดือดประมาณ 30 นาทีจนสุก' },
      { step: 2, instruction: 'ระหว่างรอไก่สุก นำข้าวหอมมะลิไปล้างน้ำ 2–3 ครั้ง' },
      { step: 3, instruction: 'เจียวกระเทียมกับน้ำมันไก่จนหอม แล้วใส่ข้าวลงไปผัดเบา ๆ' },
      { step: 4, instruction: 'นำข้าวที่ผัดแล้วไปหุงกับน้ำซุปไก่ ประมาณ 20 นาทีจนสุก' },
      { step: 5, instruction: 'หั่นไก่เป็นชิ้นเตรียมเสิร์ฟ พร้อมแตงกวาและผักชี' },
      { step: 6, instruction: 'เสิร์ฟข้าวมันพร้อมน้ำจิ้มสูตรพิเศษ' },
    ],
  },
  {
    id: 2,
    name: 'ผัดไทยกุ้งสด',
    description: 'เส้นผัดไทยผัดกับกุ้งสด ถั่วลิสง และซอสสูตรเด็ด',
    category: 'อาหารจานเดียว',
    image: padThaiWithFreshShrimp,
    protein: 25,
    fat: 12,
    carbs: 70,
    calories: 420,
    baseIngredients: [
      { name: 'เส้นจันท์', quantity: 150, unit: 'กรัม' },
      { name: 'กุ้งสด', quantity: 200, unit: 'กรัม' },
      { name: 'ไข่ไก่', quantity: 2, unit: 'ฟอง' },
      { name: 'ถั่วงอก', quantity: 100, unit: 'กรัม' },
      { name: 'น้ำมันพืช', quantity: 2, unit: 'ช้อนโต๊ะ' },
      { name: 'กระเทียมสับ', quantity: 5, unit: 'กลีบ' },
      { name: 'หัวไชโป๊เค็ม', quantity: 20, unit: 'กรัม' },
      { name: 'น้ำมะขามเปียก', quantity: 3, unit: 'ช้อนโต๊ะ' },
      { name: 'น้ำตาลปี๊บ', quantity: 2, unit: 'ช้อนโต๊ะ' },
      { name: 'น้ำปลา', quantity: 2, unit: 'ช้อนโต๊ะ' },
    ],
    steps: [
      { step: 1, instruction: 'แช่เส้นจันท์ในน้ำ 15 นาทีจนเส้นนุ่ม' },
      { step: 2, instruction: 'ผัดกระเทียมในน้ำมันจนหอม ใส่กุ้งสดผัดจนสุก' },
      { step: 3, instruction: 'ใส่เส้นและซอส (น้ำปลา, น้ำตาลปี๊บ, น้ำมะขาม) ผัดให้เข้ากัน' },
      { step: 4, instruction: 'ใส่ไข่ ผัดให้ไข่สุกคลุกเคล้าเส้น' },
      { step: 5, instruction: 'ใส่ถั่วงอก ผัดพอให้เข้ากัน ปิดไฟ' },
      { step: 6, instruction: 'จัดเสิร์ฟพร้อมถั่วลิสงบด, พริกป่น, มะนาว และกุ้งแห้ง' },
    ],
  },
  {
    id: 3,
    name: 'ต้มยำกุ้ง',
    description: 'ซุปต้มยำรสเผ็ดเปรี้ยว ใส่กุ้งสดและสมุนไพรไทย',
    category: 'ซุป',
    image: tomYumKung,
    protein: 20,
    fat: 8,
    carbs: 10,
    calories: 150,
    baseIngredients: [
      { name: 'กุ้งสด', quantity: 200, unit: 'กรัม' },
      { name: 'น้ำเปล่า', quantity: 500, unit: 'มิลลิลิตร' },
      { name: 'ตะไคร้', quantity: 2, unit: 'ต้น' },
      { name: 'ใบมะกรูด', quantity: 3, unit: 'ใบ' },
      { name: 'ข่า', quantity: 2, unit: 'แง่ง' },
      { name: 'พริกขี้หนู', quantity: 5, unit: 'เม็ด' },
      { name: 'หอมแดง', quantity: 3, unit: 'หัว' },
      { name: 'น้ำปลา', quantity: 2, unit: 'ช้อนโต๊ะ' },
      { name: 'น้ำมะนาว', quantity: 1, unit: 'ช้อนโต๊ะ' },
    ],
    steps: [
      { step: 1, instruction: 'ต้มตะไคร้, ข่า, ใบมะกรูด และหอมแดงในน้ำ 5 นาที' },
      { step: 2, instruction: 'ใส่กุ้งสด และเห็ดฟาง (ถ้ามี) ต้มจนสุก' },
      { step: 3, instruction: 'ปรุงรสด้วยน้ำปลา, น้ำมะนาว, พริกขี้หนู' },
      { step: 4, instruction: 'ยกลงจัดเสิร์ฟ โรยผักชี' },
    ],
  },
  {
    id: 4,
    name: 'แกงเขียวหวานไก่',
    description: 'แกงเขียวหวานรสเข้มข้น ใส่ไก่และมะเขือพวง',
    category: 'แกง',
    image: greenCurryWithChicken,
    protein: 30,
    fat: 25,
    carbs: 15,
    calories: 400,
    baseIngredients: [
      { name: 'ไก่สับ', quantity: 200, unit: 'กรัม' },
      { name: 'พริกแกงเขียวหวาน', quantity: 2, unit: 'ช้อนโต๊ะ' },
      { name: 'กะทิ', quantity: 200, unit: 'มิลลิลิตร' },
      { name: 'มะเขือพวง', quantity: 50, unit: 'กรัม' },
      { name: 'น้ำตาลปี๊บ', quantity: 1, unit: 'ช้อนชา' },
      { name: 'น้ำปลา', quantity: 2, unit: 'ช้อนโต๊ะ' },
      { name: 'ใบโหระพา', quantity: 5, unit: 'ใบ' },
    ],
    steps: [
      { step: 1, instruction: 'ตั้งกะทิบนเตาใส่พริกแกงเขียวหวาน คนให้เข้ากัน' },
      { step: 2, instruction: 'ใส่ไก่สับลงไปผัดจนเริ่มสุก' },
      { step: 3, instruction: 'เติมกะทิที่เหลือ ใส่มะเขือพวงและมะเขือเปราะ (ถ้ามี) เคี่ยวจนสุก' },
      { step: 4, instruction: 'ปรุงรสด้วยน้ำปลา น้ำตาลปี๊บ' },
      { step: 5, instruction: 'ปิดไฟ โรยใบโหระพา จัดเสิร์ฟร้อน ๆ' },
    ],
  },
  {
    id: 5,
    name: 'ส้มตำไทย',
    description: 'ส้มตำไทยรสหวาน เปรี้ยว เผ็ด พร้อมถั่วลิสงและมะเขือเทศ',
    category: 'ยำ',
    image: thaiPapayaSalad,
    protein: 5,
    fat: 5,
    carbs: 20,
    calories: 120,
    baseIngredients: [
      { name: 'มะละกอสุก 80%', quantity: 200, unit: 'กรัม' },
      { name: 'มะเขือเทศ', quantity: 2, unit: 'ลูก' },
      { name: 'ถั่วฝักยาว', quantity: 50, unit: 'กรัม' },
      { name: 'กระเทียม', quantity: 3, unit: 'กลีบ' },
      { name: 'พริกขี้หนู', quantity: 5, unit: 'เม็ด' },
      { name: 'น้ำมะนาว', quantity: 2, unit: 'ช้อนโต๊ะ' },
      { name: 'น้ำตาลปี๊บ', quantity: 1, unit: 'ช้อนโต๊ะ' },
      { name: 'น้ำปลา', quantity: 1, unit: 'ช้อนโต๊ะ' },
    ],
    steps: [
      { step: 1, instruction: 'โขลกกระเทียมและพริกขี้หนูพอหยาบ' },
      { step: 2, instruction: 'ใส่ถั่วฝักยาว มะเขือเทศ และมะละกอ โขลกเบา ๆ' },
      { step: 3, instruction: 'เติมน้ำมะนาว น้ำปลา และน้ำตาลปี๊บ คลุกให้เข้ากัน' },
      { step: 4, instruction: 'ใส่กุ้งแห้งและถั่วลิสงคั่ว คลุกพอเข้ากัน จัดเสิร์ฟ' },
    ],
  },
];
